// src/routes/hero.svelte
<section
	class="dark:from-violet-600 -mx-8 bg-gradient-to-b from-white to-pink-100 px-7 py-12 dark:to-violet-900"
>
	<h1
		class="max-w-2xl font-heading text-2xl font-semibold text-violet-700 dark:text-slate-100 lg:max-w-2xl lg:text-5xl lg:font-medium"
	>
		Hi, I'm Thiago Temple. I love building products, writing code and learning through it.
	</h1>
	<p class="mt-8 hidden max-w-2xl px-1 text-lg text-zinc-600 dark:text-slate-200 lg:block">
		I'm a web-loving staff developer, driven by curiosity and a passion for learning. I'm eager to
		share my knowledge and always up for new challenges. With a friendly and open-minded approach, I
		embrace the ever-evolving world of web technologies, staying ahead of the game and inspiring
		others along the way.
	</p>
</section>

// app/routes/_index/components/Hero.tsx
export function Hero() {
	return (
		<section className="bg-gradient-to-b from-[#921D6403] to-[#921D6435] px-4 py-12 text-fuchsia-500 dark:from-violet-300 dark:to-violet-500/50 md:px-6 lg:px-8 lg:py-20">
			<h1 className="font-heading  text-2xl text-violet-500 dark:text-slate-100 lg:max-w-2xl lg:text-5xl lg:font-medium">
				Hi, I'm Thiago Temple. I love building products, writing code and
				learning through it.
			</h1>
			<p className="lg: mt-8 hidden max-w-2xl text-lg text-zinc-600 dark:text-slate-200 lg:block">
				I'm a web-loving staff developer, driven by curiosity and a passion for
				learning. I'm eager to share my knowledge and always up for new
				challenges. With a friendly and open-minded approach, I embrace the
				ever-evolving world of web technologies, staying ahead of the game and
				inspiring others along the way.
			</p>
		</section>
	);
}
